### Consolidando os preços históricos de cada título

#### Problemas encontrados:
 - Nome das colunas;
 - Formato da data do dia 23/08 para alguns arquivos (número e não texto, apesar de parecerem iguais no excel)
 - Formato das datas finais de alguns arquivos em número (visível no excel)

In [153]:
%matplotlib inline  
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from os import listdir
from os.path import isfile, join
import datetime

dirPrecosInput = "D:\\Documents\\Tese\\2018\\dados\\NTNB\\"
dirPrecosOutput = "D:\\Documents\\Tese\\2018\\dados\\csv\\"
date_format = '%d/%m/%Y'

In [154]:
# para arquivo listado no diretorio informado
# atenção que a função passa por TODOS os arquivos. Aqui assumo que terá somente os arquivos necessários
dfFinal = pd.DataFrame()
for f in listdir(dirPrecosInput):
    if isfile(join(dirPrecosInput, f)):
        # Load spreadsheet
        xl = pd.ExcelFile(dirPrecosInput + f)
        # ha uma diferenca no nome da coluna nos arquivos historicos (< 2012)    
        if "historico" in f:
            strColPU = 'PU Extrato 9:00'
        else:
            strColPU = 'PU Base Manhã'
        # Importo tudo e capturo o vencimento do bond
        df1 = xl.parse(0)
        dtVcto = df1.columns[1]

        # depois eu importo excluindo a primeira linha e parseando as datas como index
        df1 = xl.parse(0, header =1, index_col =0, parse_dates = True)

        dfAll = [] # guarda todas as colunas do arquivo
        dtVcto = [] # vetor com as datas de vencimento para cada sheet

        for i in range(0, len(xl.sheet_names)):
#             print(f)
#             print(xl.sheet_names[i])
            # primeiro eu importo tudo e capturo o vencimento do bond
            df1 = xl.parse(i)
            if isinstance(df1.columns[1], datetime.date):
                dtVcto.append(str(df1.columns[1].strftime(date_format)))
            else:
                dtVcto.append(str(df1.columns[1]))
            # depois eu importo excluindo a primeira linha e leio as datas como index e uso o date_format como modelo da data
            df1 = xl.parse(i, header =1, index_col =0) # i aqui é a referencia numerica da sheet que estou lendo
            df1.index = pd.to_datetime(df1.index, format=date_format)
            dfAll.append(df1)

        # df utilizado para armazenar somente uma coluna 'PU Base Manhã', mas poderia ser outra
        df = []
        for i in range(0, len(dfAll)):
            df.append(dfAll[i][strColPU])
            df[i].name = str(dtVcto[i])
        df3 = pd.concat(df, axis=1)
#         df3 = pd.merge(df[0], df[1], left_index=True, right_index=True)
#         print(df3.head())
        dfFinal = pd.concat([dfFinal, df3], sort=True)

# Reordena antes de importar
cols = list(dfFinal.columns.values)
cols

colsDate = []
sortedCol = []
for col in cols:
    colsDate.append(datetime.datetime.strptime(col, '%d/%m/%Y'))
sorted(colsDate)
for col in sorted(colsDate):
#     print(str(col.strftime('%d/%m/%Y')))
    sortedCol.append(str(col.strftime('%d/%m/%Y')))
dfFinal = dfFinal[sortedCol]

# importa o arquivo para CSV
dfFinal.dropna(how="all").to_csv(dirPrecosOutput + str(f).replace(".xls","") + ".csv" )
# print(dirPrecosOutput + str(f).replace(".xls","") + ".csv")
# print(dfFinal.fillna(0).tail())

In [123]:
dfFinal['2005-12-25':'2006-01-10']

,07/01/2004,01/04/2004,01/07/2004,01/10/2004,04/01/2005,01/04/2005,01/07/2005,01/10/2005,01/01/2006,01/04/2006,...,01/01/2014,01/01/2015,01/01/2016,01/01/2017,01/01/2018,01/01/2019,01/01/2020,01/01/2021,01/01/2023,01/01/2025
Dia,,,,,,,,,,,,,,,,,,,,,
2005-12-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,996.69,957.17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-12-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,997.35,957.81,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,998.01,958.45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,959.06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-12-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,959.74,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,960.34,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,960.99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,961.69,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,962.31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,962.92,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,963.56,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,964.17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN